#!/usr/bin/env python3
"""Installation script for SSH"""

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "script"))
from helpers import (
    AI_KEY_PATH,
    AI_KEY_PUB_PATH,
    SSH_ASKPASS_AI_PATH,
    SSH_CONFIG_AI_PATH,
    SSH_CONFIG_DIR,
    chmod,
    dry,
    find_ssh_key,
    get_machine_ssh_config,
    info,
    install_symlinks,
    is_dry_run,
    make_dir,
    op_read_command,
    parse_dry_run,
    success,
    touch_file,
    warn,
    write_file,
)


def op_write_secret(op_account, op_ref, filename, mode="0600"):
    subprocess.run(
        [
            "op",
            "read",
            "--account",
            op_account,
            "-f",
            "-o",
            filename,
            "--file-mode",
            mode,
            op_ref,
        ],
        check=True,
    )


def write_ai_ssh_key(op_account, op_vault, ai_key_name):
    if is_dry_run():
        dry(f"would write {AI_KEY_PATH}")
        return
    op_public_ref = f"op://{op_vault}/{ai_key_name}/public key"
    op_write_secret(op_account, op_public_ref, str(AI_KEY_PUB_PATH), mode="0644")
    if not AI_KEY_PATH.exists():
        warn(
            f"{AI_KEY_PATH} does not exist!\n"
            "  Export\n\n"
            f"    {ai_key_name}\n\n"
            "  from\n\n"
            f"    {op_account}/{op_vault}\n\n"
            "  (with the right password)"
        )


def write_ai_askpass(op_ref, op_account):
    askpass_path = SSH_ASKPASS_AI_PATH
    if is_dry_run():
        if not op_ref:
            dry(f"would remove stale {askpass_path}")
        else:
            dry(f"would generate {askpass_path}")
        return

    if not op_ref:
        if askpass_path.exists():
            askpass_path.unlink()
            info(f"Removed stale {askpass_path}")
        return

    content = (
        "#!/bin/sh\n"
        "# Generated by ssh/install.py - do not edit by hand\n"
        "# SSH_ASKPASS helper: prints the AI SSH key passphrase.\n"
        f"exec {op_read_command({'ref': op_ref, 'account': op_account})}\n"
    )

    if askpass_path.exists() and askpass_path.read_text() == content:
        chmod(askpass_path, 0o700)
        success("SSH askpass helper for AI already up to date")
        return

    write_file(askpass_path, content, mode=0o700)
    success(f"Generated {askpass_path}")


def write_ai_ssh_config():
    config_ai_path = SSH_CONFIG_AI_PATH
    if is_dry_run():
        dry(f"would generate {config_ai_path}")
        return
    content = (
        "# Generated by ssh/install.py — do not edit by hand\n"
        "# Used by AI sessions only, via core.sshCommand in\n"
        "# ~/.config/git/config.ai.\n"
        "\n"
        f"IdentityFile {AI_KEY_PATH}\n"
        "IdentitiesOnly yes\n"
        "IdentityAgent SSH_AUTH_SOCK\n"
        "\n"
        "Include config.local\n"
    )

    if config_ai_path.exists() and config_ai_path.read_text() == content:
        success(f"SSH config {config_ai_path} for AI already up to date")
        return

    write_file(config_ai_path, content, mode=0o600)
    success(f"Generated {config_ai_path}")


def configure_ai_ssh():
    ai_key_name = get_machine_ssh_config().get("aiKey")
    if ai_key_name is None:
        info("No aiKey configured")
        return

    ssh_key = find_ssh_key(ai_key_name)
    if ssh_key is None:
        warn(f"aiKey {ai_key_name} not found in config")
        return

    op_vault = ssh_key["op_vault"]
    op_account = ssh_key["op_account"]
    op_ref = f"op://{op_vault}/{ai_key_name}/password"

    write_ai_ssh_key(op_account, op_vault, ai_key_name)
    write_ai_askpass(op_ref, op_account)
    write_ai_ssh_config()


def main():
    info("Configuring SSH...")
    parse_dry_run()

    topic_dir = Path(__file__).resolve().parent

    make_dir(SSH_CONFIG_DIR, mode=0o700)
    touch_file(SSH_CONFIG_DIR / "config.local")
    install_symlinks(topic_dir)
    configure_ai_ssh()

    success("SSH configured")
    return 0


if __name__ == "__main__":
    sys.exit(main())
