#!/usr/bin/env python3
"""Installation script for SSH.

Besides the ssh config and the AI signing key, this sets up an ssh-agent
for the AI key on Linux. macOS has one from launchd already; Linux has
nothing by default, and the 1Password agent only serves keys stored in
1Password, not the on-disk AI key. Without an agent, every AI session
over SSH fails at the first signed commit.
"""

import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "script"))
from helpers import (
    AI_KEY_PATH,
    AI_KEY_PUB_PATH,
    HOME,
    IS_LINUX,
    IS_MACOS,
    IS_WSL,
    OP_LINUX_AGENT_SOCKET,
    SSH_ASKPASS_AI_PATH,
    SSH_CONFIG_AI_PATH,
    SSH_CONFIG_DIR,
    SSH_SIGN_BRIDGE_PATH,
    XDG_CONFIG_HOME,
    chmod,
    dry,
    find_ssh_key,
    get_machine_ssh_config,
    info,
    install_symlinks,
    is_dry_run,
    make_dir,
    op_read_command,
    parse_dry_run,
    run_cmd,
    success,
    systemctl_enable,
    touch_file,
    warn,
    write_file,
)

SSH_CONFIG_AGENT_PATH = SSH_CONFIG_DIR / "config.agent"

# Where the 1Password desktop app exposes its SSH agent. macOS puts it in
# the app group container; the Linux app uses a plain dot-directory, and
# under WSL 1password/install.py bridges the Windows app's agent into that
# same Linux path. Neither path is configurable in the app, so this is a
# lookup, not a setting we get to choose.
OP_AGENT_SOCKET = (
    HOME / "Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    if IS_MACOS
    else OP_LINUX_AGENT_SOCKET
)


# The ssh-agent for the AI key on Linux. Arch's openssh ships a
# socket-activated user unit pair (ssh-agent.socket / .service) listening
# here; where a distro does not, an equivalent service is written below.
# `%t` is systemd for $XDG_RUNTIME_DIR.
AGENT_SOCKET_UNIT = "ssh-agent.socket"
AGENT_SERVICE_UNIT = "ssh-agent.service"
AGENT_SOCKET_PATH = "${XDG_RUNTIME_DIR}/ssh-agent.socket"
AGENT_SERVICE_PATH = XDG_CONFIG_HOME / "systemd" / "user" / AGENT_SERVICE_UNIT
AGENT_ENVIRONMENT_D = XDG_CONFIG_HOME / "environment.d" / "20-ssh-agent.conf"
AGENT_ENVIRONMENT_CONTENT = (
    "# Generated by ssh/install.py — do not edit by hand\n"
    "# Points graphical-session programs at the ssh-agent user unit, which\n"
    "# holds the AI signing key (see ssh/ssh.sh for shells).\n"
    f"SSH_AUTH_SOCK={AGENT_SOCKET_PATH}\n"
)


def _agent_service_content(ssh_agent):
    return (
        "# Generated by ssh/install.py — do not edit by hand\n"
        "# Stand-in for the ssh-agent user unit Arch's openssh ships; this\n"
        "# distro's openssh has none.\n"
        "[Unit]\n"
        "Description=OpenSSH key agent\n"
        "\n"
        "[Service]\n"
        f"ExecStart={ssh_agent} -D -a %t/ssh-agent.socket\n"
        "SuccessExitStatus=2\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def _user_unit_exists(unit):
    result = run_cmd(["systemctl", "--user", "cat", unit], check=False, capture_output=True)
    return result.returncode == 0


def configure_ssh_agent():
    """Run an ssh-agent as a systemd user unit and publish its socket.

    Linux only. Prefers the distro's own `ssh-agent.socket` user unit and
    writes an equivalent `ssh-agent.service` when there is none. Either
    way the socket ends up at $XDG_RUNTIME_DIR/ssh-agent.socket, which
    ssh/ssh.sh exports as SSH_AUTH_SOCK for shells and the environment.d
    drop-in exports for the graphical session. Loading the AI key into it
    stays the shell hook's job: it needs the passphrase.
    """
    if not IS_LINUX:
        return True
    if not shutil.which("systemctl"):
        warn("systemctl is not available; not setting up an ssh-agent user unit")
        return True

    if is_dry_run():
        dry(f"would enable {AGENT_SOCKET_UNIT} if packaged, else write and enable {AGENT_SERVICE_PATH}")
        dry(f"would write {AGENT_ENVIRONMENT_D}")
        return True

    if _user_unit_exists(AGENT_SOCKET_UNIT) and not AGENT_SERVICE_PATH.exists():
        unit = AGENT_SOCKET_UNIT
    else:
        ssh_agent = shutil.which("ssh-agent")
        if not ssh_agent:
            warn("ssh-agent is not installed; not setting up its user unit")
            return True
        content = _agent_service_content(ssh_agent)
        if AGENT_SERVICE_PATH.exists() and AGENT_SERVICE_PATH.read_text() == content:
            success(f"{AGENT_SERVICE_PATH} already up to date")
        else:
            write_file(AGENT_SERVICE_PATH, content)
            result = run_cmd(["systemctl", "--user", "daemon-reload"], check=False, capture_output=True)
            if result.returncode != 0:
                warn(f"systemctl --user daemon-reload failed: {(result.stderr or '').strip()}")
                return False
            success(f"Wrote {AGENT_SERVICE_PATH}")
        unit = AGENT_SERVICE_UNIT

    if not systemctl_enable(unit, user=True):
        return False

    if AGENT_ENVIRONMENT_D.exists() and AGENT_ENVIRONMENT_D.read_text() == AGENT_ENVIRONMENT_CONTENT:
        success(f"{AGENT_ENVIRONMENT_D} already up to date")
    else:
        write_file(AGENT_ENVIRONMENT_D, AGENT_ENVIRONMENT_CONTENT)
        success(f"Wrote {AGENT_ENVIRONMENT_D} (graphical apps see it after the next login)")
    return True


def op_write_secret(op_account, op_ref, filename, mode="0600"):
    """Write the secret behind `op_ref` to `filename` with `mode`.

    Reads through stdout rather than op's own `-o`: under WSL `op` is the
    Windows op.exe (see 1password/install.py), which would resolve an `-o`
    path on the Windows side. It may also end lines with CRLF, which a key
    file must not contain.
    """
    result = subprocess.run(
        ["op", "read", "--account", op_account, op_ref],
        check=True,
        capture_output=True,
    )
    content = result.stdout.replace(b"\r\n", b"\n").decode()
    if not content.endswith("\n"):
        content += "\n"
    write_file(filename, content, mode=int(mode, 8))


def write_ai_ssh_key(op_account, op_vault, ai_key_name):
    if is_dry_run():
        dry(f"would write {AI_KEY_PATH}")
        return
    op_public_ref = f"op://{op_vault}/{ai_key_name}/public key"
    op_write_secret(op_account, op_public_ref, str(AI_KEY_PUB_PATH), mode="0644")
    if not AI_KEY_PATH.exists():
        warn(
            f"{AI_KEY_PATH} does not exist!\n"
            "  Export\n\n"
            f"    {ai_key_name}\n\n"
            "  from\n\n"
            f"    {op_account}/{op_vault}\n\n"
            "  (with the right password)"
        )


def write_ai_askpass(op_ref, op_account):
    askpass_path = SSH_ASKPASS_AI_PATH
    if is_dry_run():
        if not op_ref:
            dry(f"would remove stale {askpass_path}")
        else:
            dry(f"would generate {askpass_path}")
        return

    if not op_ref:
        if askpass_path.exists():
            askpass_path.unlink()
            info(f"Removed stale {askpass_path}")
        return

    content = (
        "#!/bin/sh\n"
        "# Generated by ssh/install.py - do not edit by hand\n"
        "# SSH_ASKPASS helper: prints the AI SSH key passphrase.\n"
        f"exec {op_read_command({'ref': op_ref, 'account': op_account})}\n"
    )

    if askpass_path.exists() and askpass_path.read_text() == content:
        chmod(askpass_path, 0o700)
        success("SSH askpass helper for AI already up to date")
        return

    write_file(askpass_path, content, mode=0o700)
    success(f"Generated {askpass_path}")


def write_agent_ssh_config():
    """Generate ~/.ssh/config.agent, pointing ssh at the 1Password agent.

    ~/.ssh/config includes this file rather than hard-coding the socket,
    because the path differs between the macOS and Linux 1Password apps.
    """
    socket_path = OP_AGENT_SOCKET
    content = (
        "# Generated by ssh/install.py — do not edit by hand\n"
        "# Points ssh at the 1Password desktop app's SSH agent.\n"
        f'IdentityAgent "{socket_path}"\n'
    )

    if is_dry_run():
        dry(f"would generate {SSH_CONFIG_AGENT_PATH} -> {socket_path}")
        return

    if (
        SSH_CONFIG_AGENT_PATH.exists()
        and SSH_CONFIG_AGENT_PATH.read_text() == content
    ):
        chmod(SSH_CONFIG_AGENT_PATH, 0o600)
        success(f"SSH config {SSH_CONFIG_AGENT_PATH} already up to date")
        return

    write_file(SSH_CONFIG_AGENT_PATH, content, mode=0o600)
    success(f"Generated {SSH_CONFIG_AGENT_PATH}")


def write_bridge_sign_helper():
    """Generate git's gpg.ssh.program for WSL.

    op-ssh-sign is part of the desktop app, which under WSL runs on the
    Windows host, so sign with ssh-keygen against the bridged 1Password
    agent instead. git hands over the public key (user.signingkey) and
    ssh-keygen finds the private half in the agent.
    """
    content = (
        "#!/bin/sh\n"
        "# Generated by ssh/install.py - do not edit by hand\n"
        "# git gpg.ssh.program under WSL: sign with ssh-keygen through the\n"
        "# bridged Windows 1Password SSH agent (see 1password/install.py).\n"
        f'export SSH_AUTH_SOCK="{OP_LINUX_AGENT_SOCKET}"\n'
        'exec ssh-keygen "$@"\n'
    )
    if is_dry_run():
        dry(f"would generate {SSH_SIGN_BRIDGE_PATH}")
        return
    if SSH_SIGN_BRIDGE_PATH.exists() and SSH_SIGN_BRIDGE_PATH.read_text() == content:
        chmod(SSH_SIGN_BRIDGE_PATH, 0o700)
        success("SSH signing helper for the 1Password bridge already up to date")
        return
    write_file(SSH_SIGN_BRIDGE_PATH, content, mode=0o700)
    success(f"Generated {SSH_SIGN_BRIDGE_PATH}")


def write_ai_ssh_config():
    config_ai_path = SSH_CONFIG_AI_PATH
    if is_dry_run():
        dry(f"would generate {config_ai_path}")
        return
    content = (
        "# Generated by ssh/install.py — do not edit by hand\n"
        "# Used by AI sessions only, via core.sshCommand in\n"
        "# ~/.config/git/config.ai.\n"
        "\n"
        f"IdentityFile {AI_KEY_PATH}\n"
        "IdentitiesOnly yes\n"
        "IdentityAgent SSH_AUTH_SOCK\n"
        "\n"
        "Include config.local\n"
    )

    if config_ai_path.exists() and config_ai_path.read_text() == content:
        success(f"SSH config {config_ai_path} for AI already up to date")
        return

    write_file(config_ai_path, content, mode=0o600)
    success(f"Generated {config_ai_path}")


def configure_ai_ssh():
    ai_key_name = get_machine_ssh_config().get("aiKey")
    if ai_key_name is None:
        info("No aiKey configured")
        return

    ssh_key = find_ssh_key(ai_key_name)
    if ssh_key is None:
        warn(f"aiKey {ai_key_name} not found in config")
        return

    op_vault = ssh_key["op_vault"]
    op_account = ssh_key["op_account"]
    op_ref = f"op://{op_vault}/{ai_key_name}/password"

    write_ai_ssh_key(op_account, op_vault, ai_key_name)
    write_ai_askpass(op_ref, op_account)
    write_ai_ssh_config()


def main():
    info("Configuring SSH...")
    parse_dry_run()

    topic_dir = Path(__file__).resolve().parent

    make_dir(SSH_CONFIG_DIR, mode=0o700)
    touch_file(SSH_CONFIG_DIR / "config.local")
    write_agent_ssh_config()
    if IS_WSL:
        write_bridge_sign_helper()
    install_symlinks(topic_dir)
    if not configure_ssh_agent():
        return 1
    configure_ai_ssh()

    success("SSH configured")
    return 0


if __name__ == "__main__":
    sys.exit(main())
