#!/usr/bin/env python3
"""Installation script for SSH"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'script'))
from helpers import (
    dry,
    get_machine_config,
    get_short_hostname,
    info,
    install_symlinks,
    is_dry_run,
    op_read_command,
    parse_dry_run,
    success,
    warn,
    write_file,
)


CLAUDE_SBP_GITLAB_KEY_NAME = 'claude_sbp_gitlab_ed25519'
SBP_GITLAB_HOST = 'sbp.gitlab.schubergphilis.com'


def _generate_askpass(askpass_path, secret_value, label):
    """Write an SSH_ASKPASS helper that prints a 1Password secret.

    ``secret_value`` is whatever was read from machine config — a
    bare ``op://...`` string or an object with ``ref``/``account``.
    Falsy means "no secret configured for this machine"; in that
    case we delete any stale helper and return.
    """
    if not secret_value:
        if askpass_path.exists():
            if is_dry_run():
                dry(f"would remove stale {askpass_path}")
            else:
                askpass_path.unlink()
                info(f"Removed stale {askpass_path}")
        return

    content = (
        '#!/bin/sh\n'
        '# Generated by ssh/install.py — do not edit by hand\n'
        f'# SSH_ASKPASS helper: prints the {label} passphrase.\n'
        f'exec {op_read_command(secret_value)}\n'
    )

    if askpass_path.exists() and askpass_path.read_text() == content:
        success(f"SSH askpass helper ({label}) already up to date")
        return

    write_file(askpass_path, content, mode=0o700)
    success(f"Generated {askpass_path}")


def generate_claude_askpass():
    """Generate an SSH_ASKPASS helper that fetches the claude signing
    key passphrase from 1Password.

    On shells where ``ssh.claudeSigningKey`` is configured,
    ``ssh/ssh.sh`` invokes this helper to add the claude signing key
    to ssh-agent without an interactive prompt. Calling ``op read``
    also unlocks 1Password biometric for the session, so the first
    op-ssh-sign-backed git commit afterwards doesn't have to.
    """
    home = Path.home()
    xdg_config_home = Path(os.environ.get('XDG_CONFIG_HOME', home / '.config'))
    askpass = xdg_config_home / 'dotfiles' / 'ssh-askpass-claude.sh'

    machine_config, _ = get_machine_config()
    secret = machine_config.get('ssh', {}).get('claudeSigningKey')

    _generate_askpass(askpass, secret, 'claude signing key')


def generate_claude_sbp_gitlab_askpass():
    """Generate an SSH_ASKPASS helper that fetches the dedicated sbp
    gitlab auth key passphrase from 1Password.

    Mirrors :func:`generate_claude_askpass`. The dedicated key
    (``~/.ssh/claude_sbp_gitlab_ed25519``) is loaded into ssh-agent
    at terminal startup by ``ssh/ssh.sh`` so that Claude sessions
    can push/pull/clone sbp gitlab repos even when 1Password is
    locked.
    """
    home = Path.home()
    xdg_config_home = Path(os.environ.get('XDG_CONFIG_HOME', home / '.config'))
    askpass = xdg_config_home / 'dotfiles' / 'ssh-askpass-claude-sbp-gitlab.sh'

    machine_config, _ = get_machine_config()
    secret = machine_config.get('ssh', {}).get('claudeSbpGitlabKey')

    _generate_askpass(askpass, secret, 'claude sbp gitlab key')


def generate_ssh_config_claude():
    """Write ~/.ssh/config.claude.

    A claude-only ssh config: routes sbp gitlab through the standard
    ssh-agent (where the dedicated key is loaded) using the dedicated
    on-disk identity. Other hosts fall through to the main
    ~/.ssh/config via Include, so github etc. continue to use the
    1Password agent normally.

    This file is referenced from ~/.config/git/config.claude via
    core.sshCommand=`ssh -F ~/.ssh/config.claude`. Because Claude
    sessions already set GIT_CONFIG_GLOBAL to config.claude (see
    claude/install.py), this routing only applies inside Claude.
    """
    config_claude = Path.home() / '.ssh' / 'config.claude'
    key_path = Path.home() / '.ssh' / CLAUDE_SBP_GITLAB_KEY_NAME

    content = (
        '# Generated by ssh/install.py — do not edit by hand\n'
        '# Used by Claude sessions only, via core.sshCommand in\n'
        '# ~/.config/git/config.claude.\n'
        '\n'
        f'Host {SBP_GITLAB_HOST}\n'
        f'    HostName {SBP_GITLAB_HOST}\n'
        '    Port 2228\n'
        '    User git\n'
        f'    IdentityFile {key_path}\n'
        '    IdentitiesOnly yes\n'
        '    IdentityAgent SSH_AUTH_SOCK\n'
        '\n'
        'Include config\n'
    )

    if config_claude.exists() and config_claude.read_text() == content:
        success("SSH config.claude already up to date")
        return

    write_file(config_claude, content, mode=0o600)
    success(f"Generated {config_claude}")


def warn_if_claude_sbp_gitlab_key_missing():
    """Print recovery instructions if the dedicated sbp gitlab key isn't on disk."""
    priv_key = Path.home() / '.ssh' / CLAUDE_SBP_GITLAB_KEY_NAME
    pub_key = priv_key.with_suffix('.pub')

    if is_dry_run() or priv_key.exists():
        return

    machine_config, _ = get_machine_config()
    secret = machine_config.get('ssh', {}).get('claudeSbpGitlabKey')
    if not secret:
        # No password ref configured for this machine — this key
        # isn't expected here. Stay quiet.
        return

    hostname = get_short_hostname()
    warn(f"Claude sbp gitlab key missing: {priv_key}")
    info("Create it with:")
    info("")
    info(
        f"  ssh-keygen -t ed25519 -C 'claude-sbp-gitlab@{hostname}' "
        f"-f {priv_key}"
    )
    info("  # Enter a passphrase when prompted, then save it to 1Password:")
    info(
        f"  op item create --category=password "
        f"--title='Claude SBP GitLab SSH Key ({hostname})' "
        f"--vault=<vault> password=<passphrase>"
    )
    info(
        "  # Update machines/<host>.json ssh.claudeSbpGitlabKey to point to it:"
    )
    info(
        "  # { \"ref\": \"op://<vault>/<item>/password\", \"account\": \"<acct>\" }"
    )
    info("")
    info("  # Then register the public key on sbp gitlab as an *authentication* key:")
    info(f"  cat {pub_key}")
    info(
        "  # Paste at "
        "https://sbp.gitlab.schubergphilis.com/-/user_settings/ssh_keys"
    )


def main():
    parse_dry_run()
    install_symlinks(Path(__file__).resolve().parent)

    info("Configuring SSH...")

    ssh_dir = Path.home() / '.ssh'
    if is_dry_run():
        dry(f"would ensure {ssh_dir} exists with mode 0700 and config.local exists")
    else:
        ssh_dir.mkdir(mode=0o700, exist_ok=True)

        # Ensure correct permissions
        current_mode = ssh_dir.stat().st_mode & 0o777
        if current_mode != 0o700:
            ssh_dir.chmod(0o700)
            info(f"Fixed ~/.ssh permissions: {oct(current_mode)} -> 0700")

        # Create empty config.local if it doesn't exist
        config_local = ssh_dir / 'config.local'
        if not config_local.exists():
            config_local.touch(mode=0o600)
            info("Created ~/.ssh/config.local")

    generate_claude_askpass()
    generate_claude_sbp_gitlab_askpass()
    generate_ssh_config_claude()
    warn_if_claude_sbp_gitlab_key_missing()

    success("SSH configured")
    return 0


if __name__ == '__main__':
    sys.exit(main())
