# Point SSH_AUTH_SOCK at the ssh-agent user unit ssh/install.py enables on
# Linux, unless the environment already has an agent (macOS via launchd,
# a forwarded agent, the systemd environment.d drop-in). SSH logins get
# no systemd user environment, so this is what covers them. Runs for
# non-interactive shells too: AI tools spawn those for git.
if [ -z "${SSH_AUTH_SOCK:-}" ] && [ -S "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/ssh-agent.socket" ]; then
  export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/ssh-agent.socket"
fi

# Auto-load the AI SSH key into ssh-agent on first login.
#
# Side effect: invoking `op read` to fetch the passphrase also unlocks
# 1Password biometric for the session, so subsequent op-ssh-sign git
# operations don't prompt mid-task.
#
# Only runs in interactive shells with ssh-agent reachable, when the
# askpass helper generated by ssh/install.py exists, and when the key
# isn't already loaded. When the 1Password route fails (no desktop app
# to approve the read, as over SSH), it says so once per shell rather
# than leaving the first signed commit to discover it.

# shellcheck disable=SC2317
# The finding is on the `|| true`, which is reachable only when this file is
# *executed* rather than sourced -- the case the fallback exists for, since
# `return` outside a function fails there. In the normal sourced case `return`
# does exit early and shellcheck is correct that the fallback is dead code; the
# fallback is kept for the other case anyway.
case $- in
  *i*) ;;
  *) return 0 2>/dev/null || true ;;
esac

_dotfiles_ssh_askpass_ai="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/ssh-askpass-ai.sh"
_dotfiles_ai_key="$HOME/.ssh/ai_ed25519"

if [ -x "$_dotfiles_ssh_askpass_ai" ] \
  && [ -f "$_dotfiles_ai_key" ] \
  && [ -n "${SSH_AUTH_SOCK:-}" ] \
  && command -v op > /dev/null 2>&1 \
  && command -v ssh-add > /dev/null 2>&1 \
  && command -v ssh-keygen > /dev/null 2>&1; then
  _dotfiles_ai_fp=$(ssh-keygen -lf "$_dotfiles_ai_key" 2>/dev/null | awk '{print $2}')
  if [ -n "$_dotfiles_ai_fp" ] \
    && ! ssh-add -l 2>/dev/null | grep -q -- "$_dotfiles_ai_fp"; then
    DISPLAY="${DISPLAY:-:0}" \
      SSH_ASKPASS="$_dotfiles_ssh_askpass_ai" \
      SSH_ASKPASS_REQUIRE=force \
      ssh-add "$_dotfiles_ai_key" </dev/null > /dev/null 2>&1 \
      || echo "ssh: AI signing key not loaded (1Password unavailable); run: ssh-add $_dotfiles_ai_key" >&2
  fi
  unset _dotfiles_ai_fp
fi

unset _dotfiles_ssh_askpass_ai _dotfiles_ai_key
