# Auto-load the AI SSH key into ssh-agent on first login.
#
# Side effect: invoking `op read` to fetch the passphrase also unlocks
# 1Password biometric for the session, so subsequent op-ssh-sign git
# operations don't prompt mid-task.
#
# Only runs in interactive shells with ssh-agent reachable, when the
# askpass helper generated by ssh/install.py exists, and when the key
# isn't already loaded.

case $- in
  *i*) ;;
  *) return 0 2>/dev/null || true ;;
esac

_dotfiles_ssh_askpass_ai="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/ssh-askpass-ai.sh"
_dotfiles_ai_key="$HOME/.ssh/ai_ed25519"

if [ -x "$_dotfiles_ssh_askpass" ] \
  && [ -f "$_dotfiles_ai_key" ] \
  && [ -n "${SSH_AUTH_SOCK:-}" ] \
  && command -v op > /dev/null 2>&1 \
  && command -v ssh-add > /dev/null 2>&1 \
  && command -v ssh-keygen > /dev/null 2>&1; then
  _dotfiles_ai_fp=$(ssh-keygen -lf "$_dotfiles_ai_key" 2>/dev/null | awk '{print $2}')
  if [ -n "$_dotfiles_ai_fp" ] \
    && ! ssh-add -l 2>/dev/null | grep -q -- "$_dotfiles_ai_fp"; then
    DISPLAY="${DISPLAY:-:0}" \
      SSH_ASKPASS="$_dotfiles_ssh_askpass" \
      SSH_ASKPASS_REQUIRE=force \
      ssh-add "$_dotfiles_ai_key" </dev/null > /dev/null 2>&1
  fi
  unset _dotfiles_ai_fp
fi

unset _dotfiles_ssh_askpass _dotfiles_ai_key
