#!/usr/bin/env python3
"""Installation script for Git"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "script"))
from helpers import (
    brew_install,
    brew_is_installed,
    error,
    get_machine_config,
    info,
    install_symlinks,
    parse_dry_run,
    success,
    write_file,
)


def generate_local_config():
    """Generate machine-specific git config.local"""
    home = Path.home()
    xdg_config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    config_local = xdg_config_home / "git" / "config.local"

    machine_config, hostname = get_machine_config()
    git_user = machine_config["git"]["user"]

    content = f"""# Machine-specific git configuration
# Generated by git/install.py for hostname: {hostname}

[user]
name = {git_user["name"]}
email = {git_user["email"]}
signingkey = {git_user["signingkey"]}
"""

    # Check if content changed
    if config_local.exists():
        existing = config_local.read_text()
        if existing == content:
            success(f"Git config.local already up to date ({git_user['name']})")
            return True

    write_file(config_local, content)
    name, email = git_user["name"], git_user["email"]
    success(f"Generated git config.local for {hostname}: {name} <{email}>")
    return True


def main():
    parse_dry_run()
    install_symlinks(Path(__file__).resolve().parent)

    info("Installing Git...")

    if brew_is_installed("git"):
        success("Git already installed")
    elif brew_install("git"):
        success("Git installed")
    else:
        error("Failed to install Git")
        return 1

    if brew_is_installed("git-credential-manager"):
        success("Git Credential Manager already installed")
    elif brew_install("git-credential-manager", cask=True):
        success("Git Credential Manager installed")
    else:
        error("Failed to install Git Credential Manager")
        return 1

    generate_local_config()
    return 0


if __name__ == "__main__":
    sys.exit(main())
