#!/usr/bin/env python3
"""Installation script for Git"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'script'))
from helpers import info, success, error, brew_install, brew_is_installed, get_machine_config


def generate_local_config():
    """Generate machine-specific git config.local"""
    home = Path.home()
    xdg_config_home = Path(os.environ.get('XDG_CONFIG_HOME', home / '.config'))
    config_local = xdg_config_home / 'git' / 'config.local'

    machine_config, hostname = get_machine_config()
    git_user = machine_config['git']['user']

    content = f"""# Machine-specific git configuration
# Generated by git/install.py for hostname: {hostname}

[user]
    name = {git_user['name']}
    email = {git_user['email']}
"""

    # Ensure directory exists
    config_local.parent.mkdir(parents=True, exist_ok=True)

    # Check if content changed
    if config_local.exists():
        existing = config_local.read_text()
        if existing == content:
            success(f"Git config.local already up to date ({git_user['name']})")
            return True

    config_local.write_text(content)
    success(f"Generated git config.local for {hostname}: {git_user['name']} <{git_user['email']}>")
    return True


def main():
    info("Installing Git...")

    if brew_is_installed('git'):
        success("Git already installed")
    elif brew_install('git'):
        success("Git installed")
    else:
        error("Failed to install Git")
        return 1

    generate_local_config()
    return 0


if __name__ == '__main__':
    sys.exit(main())
