#!/usr/bin/env python3
"""Installation script for Git"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "script"))
from helpers import (
    brew_install,
    brew_is_installed,
    error,
    get_machine_config,
    get_short_hostname,
    info,
    install_symlinks,
    is_dry_run,
    parse_dry_run,
    success,
    warn,
    write_file,
)


def generate_local_config():
    """Generate machine-specific git config.local"""
    home = Path.home()
    xdg_config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    config_local = xdg_config_home / "git" / "config.local"

    machine_config, hostname = get_machine_config()
    git_user = machine_config["git"]["user"]

    content = f"""# Machine-specific git configuration
# Generated by git/install.py for hostname: {hostname}

[user]
name = {git_user["name"]}
email = {git_user["email"]}
signingkey = {git_user["signingkey"]}
"""

    # Check if content changed
    if config_local.exists():
        existing = config_local.read_text()
        if existing == content:
            success(f"Git config.local already up to date ({git_user['name']})")
            return True

    write_file(config_local, content)
    name, email = git_user["name"], git_user["email"]
    success(f"Generated git config.local for {hostname}: {name} <{email}>")
    return True


def generate_allowed_signers():
    """Regenerate ~/.config/git/allowed-signers from known signing keys.

    Assembles entries from the machine's primary signing key (machine
    config) and the Claude signing key if present. Both map to the
    user's git email as principal. This file is needed for
    `git log --show-signature` (and git verify-commit) to verify SSH
    signatures without the "gpg.ssh.allowedSignersFile needs to be
    configured" error.

    Takes ownership of the file — manual additions (e.g. collaborator
    keys) will be overwritten.
    """
    home = Path.home()
    xdg_config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    allowed_signers = xdg_config_home / "git" / "allowed-signers"

    machine_config, _ = get_machine_config()
    git_user = machine_config["git"]["user"]
    email = git_user["email"]

    entries = []

    primary_pub = Path(git_user["signingkey"]).expanduser()
    if primary_pub.exists():
        entries.append(f"{email} {primary_pub.read_text().strip()}")
    else:
        warn(f"Primary signing key missing: {primary_pub}")

    claude_pub = home / ".ssh" / "claude_signing_ed25519.pub"
    if claude_pub.exists():
        entries.append(f"{email} {claude_pub.read_text().strip()}")

    content = "# Generated by git/install.py — do not edit by hand\n"
    content += "\n".join(entries) + "\n" if entries else ""

    if allowed_signers.exists() and allowed_signers.read_text() == content:
        success("Git allowed-signers already up to date")
    else:
        write_file(allowed_signers, content)
        success(f"Generated {allowed_signers} ({len(entries)} key(s))")

    return True


def generate_claude_config():
    """Generate git config for Claude Code sessions.

    Claude sessions sign with an on-disk SSH key via the stock
    `ssh-keygen` signer, bypassing op-ssh-sign so commits work inside
    sandboxed subprocesses and don't trigger 1Password prompts.
    """
    home = Path.home()
    xdg_config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
    base_config = xdg_config_home / "git" / "config"
    config_claude = xdg_config_home / "git" / "config.claude"

    priv_key = home / ".ssh" / "claude_signing_ed25519"
    pub_key = priv_key.with_suffix(priv_key.suffix + ".pub")

    content = f"""# Git config for Claude Code sessions
# Generated by git/install.py — do not edit by hand
#
# Signs commits with an on-disk SSH key via ssh-keygen instead of
# op-ssh-sign, so commits work inside sandboxes and don't prompt
# 1Password on every signature.

[include]
	path = {base_config}

[gpg "ssh"]
	program = ssh-keygen

[user]
	signingkey = {pub_key}

[commit]
	gpgsign = true
"""

    if config_claude.exists() and config_claude.read_text() == content:
        success("Git config.claude already up to date")
    else:
        write_file(config_claude, content)
        success(f"Generated {config_claude}")

    if is_dry_run() or priv_key.exists():
        return True

    hostname = get_short_hostname()
    warn(f"Claude signing key missing: {priv_key}")
    info("Create it with one of the following:")
    info("")
    info("  # 1. Generate a fresh passphrase-less key:")
    info(
        f"  ssh-keygen -t ed25519 -N '' -C 'claude@{hostname}' "
        f"-f {priv_key}"
    )
    info("")
    info("  # 2. Back it up to 1Password as a document (adjust vault):")
    info(
        f"  op document create {priv_key} "
        f"--title='Claude Signing Key ({hostname})' --vault=Private"
    )
    info("")
    info("  # 3. Register the public key on GitHub as a signing key")
    info("  # (one-time: grant gh the admin:ssh_signing_key scope):")
    info("  gh auth refresh -h github.com -s admin:ssh_signing_key")
    info(f"  gh ssh-key add --type signing --title 'claude@{hostname}' {pub_key}")
    info("")
    info("Or, if the key already exists in 1Password, restore it with:")
    info(
        f"  op document get 'Claude Signing Key ({hostname})' --vault=Private "
        f"--out-file {priv_key}"
    )
    info(f"  chmod 600 {priv_key}")
    info(f"  ssh-keygen -y -f {priv_key} > {pub_key}")

    return True


def main():
    parse_dry_run()
    install_symlinks(Path(__file__).resolve().parent)

    info("Installing Git...")

    if brew_is_installed("git"):
        success("Git already installed")
    elif brew_install("git"):
        success("Git installed")
    else:
        error("Failed to install Git")
        return 1

    if brew_is_installed("git-credential-manager"):
        success("Git Credential Manager already installed")
    elif brew_install("git-credential-manager", cask=True):
        success("Git Credential Manager installed")
    else:
        error("Failed to install Git Credential Manager")
        return 1

    if brew_is_installed("git-filter-repo"):
        success("git-filter-repo already installed")
    elif brew_install("git-filter-repo"):
        success("git-filter-repo installed")
    else:
        error("Failed to install git-filter-repo")
        return 1

    generate_local_config()
    generate_claude_config()
    generate_allowed_signers()
    return 0


if __name__ == "__main__":
    sys.exit(main())
