#!/usr/bin/env python3
"""Installation script for mise (polyglot tool version manager).

Also teaches the desktop session where mise's shims are, so GUI apps
(Zed, VS Code, IntelliJ, etc.) launched from Finder / Dock / a Wayland
launcher find mise-managed tools without a login shell:

* macOS: a LaunchAgent that extends launchd's PATH.
* Linux: a systemd ``environment.d`` drop-in, which is what the systemd
  user manager — and therefore uwsm-launched Hyprland, as Omarchy runs
  it — reads when building the session environment.
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'script'))
from helpers import (
    DOTFILES_ROOT,
    IS_LINUX,
    IS_MACOS,
    XDG_CONFIG_HOME,
    dry,
    ensure_package,
    error,
    info,
    is_dry_run,
    parse_dry_run,
    run_cmd,
    set_toml_value,
    success,
    warn,
    write_file,
)

MINIMUM_RELEASE_AGE = '7d'

# systemd reads every *.conf here when it builds the user session
# environment, before any graphical service starts.
ENVIRONMENT_D_FILE = XDG_CONFIG_HOME / 'environment.d' / '10-mise-shims.conf'


def install_mise():
    # Arch ships `mise` in extra on x86_64 only; Omarchy carries a
    # prebuilt `mise-bin` for aarch64 in its own repo. ensure_package
    # checks both names against the configured repos before it would
    # reach for a source build, so this covers either machine.
    return ensure_package(
        'mise', brew='mise', pacman='mise', aur='mise-bin', command='mise'
    )


def shims_path():
    xdg_data_home = Path(os.environ.get('XDG_DATA_HOME', Path.home() / '.local/share'))
    return xdg_data_home / 'mise' / 'shims'


def install_environment_d():
    """Add mise's shims to the systemd user session PATH.

    `environment.d` only supports variable assignment with expansion of
    variables set earlier in the same file set, so this prepends to the
    PATH systemd already has rather than replacing it.
    """
    content = (
        '# Generated by mise/install.py — do not edit by hand\n'
        '# Puts mise shims on PATH for graphical sessions, which do not\n'
        '# run a login shell and so never source the shell topics.\n'
        f'PATH={shims_path()}:${{PATH}}\n'
    )

    if is_dry_run():
        dry(f"would install systemd environment.d drop-in {ENVIRONMENT_D_FILE}")
        return True

    if ENVIRONMENT_D_FILE.exists() and ENVIRONMENT_D_FILE.read_text() == content:
        success("mise shims environment.d drop-in already up to date")
        return True

    write_file(ENVIRONMENT_D_FILE, content)
    success(
        "Installed mise shims environment.d drop-in "
        "(graphical apps will see them after the next login)"
    )
    return True


def install_gui_path_hook():
    """Make mise's shims visible to apps started outside a login shell."""
    if IS_MACOS:
        return install_launch_agent()
    if IS_LINUX:
        return install_environment_d()
    warn("No GUI PATH hook for this platform; skipping")
    return True


def install_launch_agent():
    home = Path.home()

    plist_name = 'com.lsimons.mise-gui-path.plist'
    template = DOTFILES_ROOT / 'mise' / plist_name
    agents_dir = home / 'Library' / 'LaunchAgents'
    dest = agents_dir / plist_name

    content = template.read_text().replace('__MISE_SHIMS__', str(shims_path()))

    if is_dry_run():
        dry(f"would install LaunchAgent {dest}")
        return True

    agents_dir.mkdir(parents=True, exist_ok=True)

    if dest.exists():
        run_cmd(
            ['launchctl', 'unload', str(dest)],
            capture_output=True,
            check=False,
        )

    if dest.exists() and dest.read_text() == content:
        result = run_cmd(
            ['launchctl', 'load', str(dest)],
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            error(
                "Failed to load mise-gui-path LaunchAgent: "
                f"{(result.stderr or '').strip()}"
            )
            return False
        success("mise-gui-path LaunchAgent already up to date")
        return True

    write_file(dest, content)
    result = run_cmd(
        ['launchctl', 'load', str(dest)],
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        error(
            "Failed to load mise-gui-path LaunchAgent: "
            f"{(result.stderr or '').strip()}"
        )
        return False
    success(
        "Installed mise-gui-path LaunchAgent "
        "(GUI apps will see mise shims after next login)"
    )
    return True


def ensure_minimum_release_age():
    """Ensure ~/.config/mise/config.toml sets settings.minimum_release_age.

    Only this single key is managed; the rest of the file is left untouched
    so it is not brought under version control.
    """
    config_path = XDG_CONFIG_HOME / 'mise' / 'config.toml'
    return set_toml_value(
        config_path, 'settings', 'minimum_release_age', MINIMUM_RELEASE_AGE
    )


def main():
    parse_dry_run()
    info("Installing mise...")

    if not install_mise():
        return 1

    if not ensure_minimum_release_age():
        error("Failed to configure mise minimum release age")
        return 1
    if not install_gui_path_hook():
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
