# Gemini CLI configuration
export GEMINI_SANDBOX=true

# Route git inside Gemini CLI sessions through the non-interactive AI signing
# configuration generated by the git topic.
gemini() {
  GIT_CONFIG_GLOBAL="${XDG_CONFIG_HOME:-$HOME/.config}/git/config.ai" command gemini "$@"
}
