#!/usr/bin/env python3
"""Installation script for 1Password CLI.

Under WSL the 1Password app runs on the Windows host, so this topic wires
the Linux side up to it instead of installing an app of its own: a
systemd user service bridges the Windows SSH agent into the socket path
the Linux app would use, and `op` becomes the Windows op.exe, the only
CLI that can use the app's biometric unlock.
"""

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "script"))
from helpers import (
    HOME,
    IS_WSL,
    OP_LINUX_AGENT_SOCKET,
    XDG_CONFIG_HOME,
    chmod,
    dry,
    ensure_package,
    error,
    get_machine_config,
    info,
    is_dry_run,
    make_dir,
    parse_dry_run,
    run_cmd,
    success,
    warn,
    write_file,
)

# The Windows 1Password app serves its SSH agent on this named pipe (in
# the //./pipe/... spelling npiperelay wants). npiperelay.exe, from the
# scoop extras bucket (windows/scoopfile.json), relays it over stdio and
# socat turns that into a Unix socket.
WINDOWS_AGENT_PIPE = "//./pipe/openssh-ssh-agent"
BRIDGE_SCRIPT = XDG_CONFIG_HOME / "dotfiles" / "1password-agent-bridge.sh"
BRIDGE_UNIT = XDG_CONFIG_HOME / "systemd" / "user" / "1password-agent-bridge.service"
OP_WRAPPER = HOME / ".local" / "bin" / "op"
# Where scoop puts shims for each Windows user; the fallback when the
# Windows PATH is not mirrored into this session.
WINDOWS_USERS_DIR = Path("/mnt/c/Users")

# Both the macOS and the Linux desktop app read the agent config from
# this XDG path, so nothing here is platform-specific. What does differ
# is the agent socket, which ssh/ssh.sh points SSH_AUTH_SOCK at.
OP_CONFIG_DIR = XDG_CONFIG_HOME / "1Password"
OP_SSH_CONFIG_DIR = OP_CONFIG_DIR / "ssh"
SSH_AGENT_TOML = OP_SSH_CONFIG_DIR / "agent.toml"


def migrate_legacy_config_dir():
    """Correct the historical lowercase directory when it is unambiguous."""
    if not XDG_CONFIG_HOME.exists():
        return

    entries = {entry.name: entry for entry in XDG_CONFIG_HOME.iterdir()}
    legacy = entries.get("1password")
    if legacy is None or "1Password" in entries:
        return
    if not legacy.is_dir() or legacy.is_symlink():
        warn(f"Not migrating unexpected legacy path: {legacy}")
        return

    if is_dry_run():
        dry(f"would move {legacy} to {OP_CONFIG_DIR}")
        return
    legacy.rename(OP_CONFIG_DIR)
    success(f"Migrated {legacy} to {OP_CONFIG_DIR}")


def install_1password_ssh_agent_config():
    if is_dry_run():
        dry(f"Would generate {SSH_AGENT_TOML}")
        return

    make_dir(OP_SSH_CONFIG_DIR)

    content = (
        "# Generated by 1password/install.py — do not edit by hand\n"
        "# This is the 1Password SSH agent config file, which customize the\n"
        "# behavior of the 1Password SSH agent running on this machine.\n"
        "\n#"
        "# Docs here:\n"
        "#  https://developer.1password.com/docs/ssh/agent/config\n"
        "#\n"
    )

    config, _ = get_machine_config()
    ssh_keys = config.get("ssh", {}).get("keys", [])
    for ssh_key in ssh_keys:
        auth = ssh_key.get("auth", False)
        if not auth:
            continue
        item = ssh_key["name"]
        vault = ssh_key["op_vault"]
        # agent.toml's `account` field only matches a full sign-in address,
        # email, or account UUID (e.g. "my.1password.eu") — NOT the op-CLI
        # shorthand ("my"). op_account must therefore be a sign-in address.
        # History note: commit 1fa25f5 added this `account` line using the
        # CLI shorthand, which resolves to zero identities ("agent contains
        # no identities"); f889f7f fixed the machine configs. (That commit's
        # message wrongly blamed a 1Password 8.12.28 update — it was this
        # generator change, not the app.) The secrets loader uses the
        # shorthand via `op read --account`, where it IS valid; the two
        # fields look alike but accept different values.
        account = ssh_key["op_account"]
        content += (
            "[[ssh-keys]]\n"
            f'item = "{item}"\n'
            f'vault = "{vault}"\n'
            f'account = "{account}"\n\n'
        )

    mode = 0o644
    if SSH_AGENT_TOML.exists() and SSH_AGENT_TOML.read_text() == content:
        chmod(SSH_AGENT_TOML, mode)
        success("1Password SSH agent.toml content already up to date")
        return

    write_file(SSH_AGENT_TOML, content, mode=mode)
    success(f"Generated {SSH_AGENT_TOML}")


def find_windows_exe(name):
    """Locate a Windows executable from WSL, or None.

    Interactive WSL sessions mirror the Windows PATH, so `which` usually
    finds it; scoop's shims directory is the fallback for sessions that
    do not (systemd services, sudo).
    """
    found = shutil.which(name)
    if found:
        return Path(found)
    for candidate in sorted(WINDOWS_USERS_DIR.glob(f"*/scoop/shims/{name}")):
        return candidate
    return None


def render_bridge_script(npiperelay):
    return (
        "#!/bin/sh\n"
        "# Generated by 1password/install.py - do not edit by hand\n"
        "# Bridges the Windows 1Password SSH agent (a named pipe) into the\n"
        "# Unix socket the Linux 1Password app would use, so ssh's\n"
        "# IdentityAgent and git signing work unchanged under WSL.\n"
        "set -eu\n"
        f'socket="{OP_LINUX_AGENT_SOCKET}"\n'
        'mkdir -p "$(dirname "$socket")"\n'
        'chmod 700 "$(dirname "$socket")"\n'
        'exec socat "UNIX-LISTEN:$socket,fork,mode=0600,unlink-early" \\\n'
        f'  "EXEC:{npiperelay} -ei -s {WINDOWS_AGENT_PIPE},nofork"\n'
    )


def render_bridge_unit():
    return (
        "# Generated by 1password/install.py - do not edit by hand\n"
        "[Unit]\n"
        "Description=Bridge the Windows 1Password SSH agent into WSL\n"
        "Documentation=https://developer.1password.com/docs/ssh/agent/\n"
        "\n"
        "[Service]\n"
        f"ExecStart={BRIDGE_SCRIPT}\n"
        "Restart=on-failure\n"
        "RestartSec=2\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def _write_if_changed(path, content, mode):
    """Write `content` to `path` unless identical; returns True when written."""
    if path.exists() and path.read_text() == content:
        chmod(path, mode)
        return False
    write_file(path, content, mode=mode)
    return True


def install_wsl_agent_bridge():
    """Run the agent bridge as a systemd user service.

    A service rather than a shell hook so the socket is up before the
    first ssh or git of a session and survives closed terminals. Windows
    executables run fine from systemd user units on this WSL, so no
    interop plumbing is needed. Without npiperelay on the Windows side
    the bridge is skipped with a warning rather than failing the install,
    since installing it is the Windows bootstrap's job.
    """
    info("Bridging the Windows 1Password SSH agent into WSL...")
    if not ensure_package("socat", apt="socat", command="socat"):
        return False

    npiperelay = find_windows_exe("npiperelay.exe")
    if npiperelay is None:
        warn("npiperelay.exe not found on the Windows side; skipping the SSH agent bridge")
        warn("Install it on Windows with `scoop install npiperelay` and re-run")
        return True

    script = render_bridge_script(npiperelay)
    unit = render_bridge_unit()
    if is_dry_run():
        dry(f"would install {BRIDGE_SCRIPT} and {BRIDGE_UNIT}")
        dry(f"would run: systemctl --user enable --now {BRIDGE_UNIT.name}")
        return True

    changed = _write_if_changed(BRIDGE_SCRIPT, script, 0o755)
    changed = _write_if_changed(BRIDGE_UNIT, unit, 0o644) or changed
    commands = [
        ["systemctl", "--user", "daemon-reload"],
        ["systemctl", "--user", "enable", "--now", BRIDGE_UNIT.name],
    ]
    if changed:
        commands.append(["systemctl", "--user", "restart", BRIDGE_UNIT.name])
    for command in commands:
        result = run_cmd(command, check=False, capture_output=True)
        if result.returncode != 0:
            error(f"{' '.join(command)} failed: {(result.stderr or '').strip()}")
            return False
    success(f"1Password SSH agent bridged to {OP_LINUX_AGENT_SOCKET}")
    return True


def install_op_wrapper():
    """Make `op` the Windows op.exe.

    Only the Windows CLI can use the Windows app's biometric unlock; the
    Linux CLI would need its own sign-in every session. ~/.local/bin is
    first on PATH (sh/path.sh). Returns False when op.exe is not
    available, in which case the caller installs the Linux CLI instead.
    """
    op_exe = find_windows_exe("op.exe")
    if op_exe is None:
        warn("op.exe not found on the Windows side; installing the Linux 1Password CLI instead")
        return False
    content = (
        "#!/bin/sh\n"
        "# Generated by 1password/install.py - do not edit by hand\n"
        "# Under WSL the 1Password app runs on Windows, and only its own\n"
        "# op.exe can use that app's biometric unlock.\n"
        f'exec "{op_exe}" "$@"\n'
    )
    if is_dry_run():
        dry(f"would install {OP_WRAPPER} -> {op_exe}")
        return True
    if _write_if_changed(OP_WRAPPER, content, 0o755):
        success(f"Installed {OP_WRAPPER} -> {op_exe}")
    else:
        success(f"{OP_WRAPPER} already up to date")
    return True


def main():
    parse_dry_run()
    info("Installing 1Password CLI...")

    # Fail fast, before touching any files, if this machine isn't enrolled
    # (get_machine_config() exits with an error in that case). The result
    # is cached, so install_1password_ssh_agent_config() below reuses it
    # for free.
    get_machine_config()

    migrate_legacy_config_dir()

    # Under WSL the 1Password app runs on the Windows host, so neither the
    # Linux app nor agent.toml (which only that app reads) belongs here;
    # the CLI still does.
    if IS_WSL:
        info("WSL: the Windows host runs the 1Password app; skipping app and agent.toml")
        if not install_wsl_agent_bridge():
            return 1
        if install_op_wrapper():
            return 0
    else:
        install_1password_ssh_agent_config()

        # Omarchy carries both of these in its own pacman repo, prebuilt
        # for aarch64, so neither needs the AUR.
        if not ensure_package(
            "1Password app",
            brew="1password",
            cask=True,
            macos_app="1Password",
            pacman="1password",
            apt="1password",
        ):
            return 1

    if not ensure_package(
        "1Password CLI",
        brew="1password-cli",
        cask=True,
        pacman="1password-cli",
        apt="1password-cli",
        command="op",
    ):
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
