#!/usr/bin/env python3
"""Installation script for 1Password CLI"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "script"))
from helpers import (
    XDG_CONFIG_HOME,
    brew_install,
    chmod,
    command_exists,
    dry,
    error,
    get_machine_config,
    info,
    is_dry_run,
    make_dir,
    parse_dry_run,
    success,
    warn,
    write_file,
)

OP_CONFIG_DIR = XDG_CONFIG_HOME / "1Password"
OP_SSH_CONFIG_DIR = OP_CONFIG_DIR / "ssh"
SSH_AGENT_TOML = OP_SSH_CONFIG_DIR / "agent.toml"


def migrate_legacy_config_dir():
    """Correct the historical lowercase directory when it is unambiguous."""
    if not XDG_CONFIG_HOME.exists():
        return

    entries = {entry.name: entry for entry in XDG_CONFIG_HOME.iterdir()}
    legacy = entries.get("1password")
    if legacy is None or "1Password" in entries:
        return
    if not legacy.is_dir() or legacy.is_symlink():
        warn(f"Not migrating unexpected legacy path: {legacy}")
        return

    if is_dry_run():
        dry(f"would move {legacy} to {OP_CONFIG_DIR}")
        return
    legacy.rename(OP_CONFIG_DIR)
    success(f"Migrated {legacy} to {OP_CONFIG_DIR}")


def install_1password_ssh_agent_config():
    if is_dry_run():
        dry(f"Would generate {SSH_AGENT_TOML}")
        return

    make_dir(OP_SSH_CONFIG_DIR)

    content = (
        "# Generated by 1password/install.py — do not edit by hand\n"
        "# This is the 1Password SSH agent config file, which customize the\n"
        "# behavior of the 1Password SSH agent running on this machine.\n"
        "\n#"
        "# Docs here:\n"
        "#  https://developer.1password.com/docs/ssh/agent/config\n"
        "#\n"
    )

    config, _ = get_machine_config()
    ssh_keys = config.get("ssh", {}).get("keys", [])
    for ssh_key in ssh_keys:
        auth = ssh_key.get("auth", False)
        if not auth:
            continue
        item = ssh_key["name"]
        vault = ssh_key["op_vault"]
        account = ssh_key["op_account"]
        content += (
            "[[ssh-keys]]\n"
            f'item = "{item}"\n'
            f'vault = "{vault}"\n'
            f'account = "{account}"\n\n'
        )

    mode = 0o644
    if SSH_AGENT_TOML.exists() and SSH_AGENT_TOML.read_text() == content:
        chmod(SSH_AGENT_TOML, mode)
        success("1Password SSH agent.toml content already up to date")
        return

    write_file(SSH_AGENT_TOML, content, mode=mode)
    success(f"Generated {SSH_AGENT_TOML}")


def main():
    parse_dry_run()
    info("Installing 1Password CLI...")

    migrate_legacy_config_dir()
    install_1password_ssh_agent_config()

    if Path("/Applications/1Password.app").exists():
        success("1Password app already installed")
    elif brew_install("1password", cask=True):
        success("1Password app installed")
    else:
        error("Failed to install 1Password app")
        return 1

    if command_exists("op"):
        success("1Password CLI already installed")
    elif brew_install("1password-cli", cask=True):
        success("1Password CLI installed")
    else:
        error("Failed to install 1Password CLI")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
